name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Install Allure CLI
      run: |
        sudo apt-get install -y curl unzip
        curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.zip
        unzip allure.zip -d /opt/allure
        echo "PATH=/opt/allure/allure-2.21.0/bin:$PATH" >> $GITHUB_ENV

    - name: Update Snapshots
      run: npx playwright test --update-snapshots

    - name: Run Playwright tests
      run: npx playwright test

    - name: Generate Allure Report
      run: allure generate ./allure-results -o ./allure-report --clean

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: allure-report/
        retention-days: 30
